version: '2'

services:
  electricity:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

networks:
  default:
    external:
      name: nginxle_default
